### ISSUE TITLE
Give jn9e9 the Write role

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-client-go#36]
Hi @jn9e9!

I would like to propose you to have the Write role for both `parsec-client-go` and `parsec-mock`. With that role you will be able to help us maintain those repositories by being able to approve and merge pull-requests. Find [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) a more complete description of what the Write role permits.

More than fair since all of this code is yours 😄 
Thanks for your work!!

**Comment by ionut-arm** [comment]
👍🏻 Seems more than fair to me! We can wait for the next weekly Parsec meeting if need be, but I think we can skip that

**Comment by jn9e9** [comment]
cool, thanks

**Comment by paulhowardarm** [comment]
@jn9e9 now has the Write role in this repo, and I have issued his invitation for the same role in parsec-mock.
