### ISSUE TITLE
Bring the Go client to a working state

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-client-go#4]
Bring the repo up-to-date with new logos, CI, updated `README.md`.
Bring it to a working state so that it is tested with Parsec so that some operations are working.

**Comment by paulhowardarm** [comment]
One specific piece of work needed here is to catch-up with the breaking changes to the wire protocol that were introduced with https://github.com/parallaxsecond/parsec-interface-rs/pull/48
