### ISSUE TITLE
Add automatic crypto provider and authenticator selection

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-client-go#6]
In the Rust `BasicClient`, during the constructor we automatically choose the default provider and authenticator. See [here](https://github.com/parallaxsecond/parsec-client-rust/blob/75902d454c65e44bd8dfebb492683bc260283876/src/core/basic_client.rs#L202).

They are choosen from the first entry of the `ListProviders` and `ListAuthenticators` commands. That way, once client have successfully generated on instance of the basic client, they can already start making secure crypto operations without any set-up needed 👌 

It would be nice to have something similar in the Go client! I believe all the pieces are there, it would just need some logic.

**Comment by jn9e9** [comment]
take account of this: https://github.com/parallaxsecond/parsec-client-go/pull/28#discussion_r586266126
